#ifndef __SYS__FS__FAT12_INTERNAL_H_
#define __SYS__FS__FAT12_INTERNAL_H_

#define FAT12_DIRENT_NAME_LEN 8
#define FAT12_DIRENT_EXT_LEN 3

typedef uint16_t fat12_cluster;

typedef enum 
{
	FAT12_SUCCESS = 0,
	FAT12_BAD_ARGS,
	FAT12_READ_ERROR,
	FAT12_NOT_FOUND,
	FAT12_NOT_FILE,
	FAT12_NOT_DIRECTORY,
	FAT12_ALLOC_ERROR,
} fat12_error;

#endif